[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm install -g pnpm@11.5.0 && pnpm install --frozen-lockfile && pnpm -C packages/database db:generate && pnpm -C api build"
]

[start]
cmd = "node api/dist/index.js"
