[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npx --yes pnpm@11.5.0 install --frozen-lockfile && npx pnpm@11.5.0 -C packages/database db:generate && npx pnpm@11.5.0 -C api build"]

[start]
cmd = "node api/dist/index.js"
